export default {
    'title': 'the march/rally/protest',
    'sections.before.title': 'Before',
    'sections.before.items[0]': 'Choose emergency meeting point',
    'sections.before.items[1]': 'Take photos of ID/drivers license',
    'sections.dayOf.items[0]': 'Cash',
    'sections.dayOf.items[1]': 'Water bottle',
    'sections.dayOf.items[2]': 'Snacks',
    'sections.dayOf.items[3]': 'Scarf or bandana',
    'sections.dayOf.items[4]': 'Leave pocket knife at home',
    'sections.dayOf.items[5]': 'Remove fingerprints from phone',
    'sections.dayOf.items[6]': 'Remove unnecessary stuff from wallet',
    'sections.dayOf.items[7]': 'Write phone number for lawyer on right arm',
    'sections.dayOf.items[8]': 'Write phone number for emergency contact on left arm',
    'sections.dayOf.items[9]': 'Write "EMERGENCY" on left hand with arrow pointing up arm',
    'sections.notes.title': 'Notes',
    'sections.notes.items[0]': 'Resist without violence',
    'checklist.title': title => `Checklist for ${title}`,
    'checklist.title.prefix': 'Checklist for',
    'share.message': title => `Checklist for ${title}. #ImNotOkWith staying home`,
    'share.facebook': 'Review and Post',
    'share.twitter': 'Review and Tweet',
    'footer.title': '#ImNotOkayWith staying home',
    'section.edit': 'edit',
    'section.back': 'Back',
};